// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_d5MlWmWQbQLajdwhu165UToPjYoC6_w',
    appId: '1:823188760947:web:5b458217875e29ba983d06',
    messagingSenderId: '823188760947',
    projectId: 'ozonstore-682ff',
    authDomain: 'ozonstore-682ff.firebaseapp.com',
    storageBucket: 'ozonstore-682ff.appspot.com',
    measurementId: 'G-75TMLTDZEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClA8EvSUkwDjObt2bD1j1xmsPupo_wKmA',
    appId: '1:823188760947:android:4815bd5e313d2ccf983d06',
    messagingSenderId: '823188760947',
    projectId: 'ozonstore-682ff',
    storageBucket: 'ozonstore-682ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWwIV-JZ6D-iwaFwQHkcQCY1NrMsIpFpA',
    appId: '1:823188760947:ios:9f2143aae0d9376e983d06',
    messagingSenderId: '823188760947',
    projectId: 'ozonstore-682ff',
    storageBucket: 'ozonstore-682ff.appspot.com',
    androidClientId: '823188760947-qg4nb258siv1hfpjita4cmg5jqtuo3c3.apps.googleusercontent.com',
    iosClientId: '823188760947-a9kbv69le53p8fsldr3ovv0d754s5a62.apps.googleusercontent.com',
    iosBundleId: 'com.example.ozonStore',
  );
}
